Fix tests with debug output
tests were failing in python2 with:

======================================================================
FAIL: test_1 (pony.orm.tests.test_show.TestShow)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/pony-0.7.6/pony/orm/tests/test_show.py", line 62, in test_1
    ''')
AssertionError: '\nGET~CONNECTION~FROM~THE~LOCAL~POOL\nSWITCH~TO~AUTOCOMMIT~MODE\nSELECT~"s"."id",~"s"."name",~"s"."scholarship",~"s"."gpa",~"s"."dob",~"s"."group"\nFROM~"Student"~"s"\n\nid|name|scholarship|gpa|dob~~~~~~~|group~~~\n--+----+-----------+---+----------+--------\n1~|S1~~|None~~~~~~~|3.1|None~~~~~~|Group[1]\n2~|S2~~|100~~~~~~~~|3.2|2000-01-01|Group[1]\n3~|S3~~|200~~~~~~~~|3.3|2001-01-02|Group[1]\n' != '\nid|name|scholarship|gpa|dob~~~~~~~|group~~~\n--+----+-----------+---+----------+--------\n1~|S1~~|None~~~~~~~|3.1|None~~~~~~|Group[1]\n2~|S2~~|100~~~~~~~~|3.2|2000-01-01|Group[1]\n3~|S3~~|200~~~~~~~~|3.3|2001-01-02|Group[1]\n'

======================================================================
FAIL: test_2 (pony.orm.tests.test_show.TestShow)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abuild/rpmbuild/BUILD/pony-0.7.6/pony/orm/tests/test_show.py", line 71, in test_2
    ''')
AssertionError: '\nGET~CONNECTION~FROM~THE~LOCAL~POOL\nSWITCH~TO~AUTOCOMMIT~MODE\nSELECT~"g"."number"\nFROM~"Group"~"g"\n\nnumber\n------\n1~~~~~\n2~~~~~\n' != '\nnumber\n------\n1~~~~~\n2~~~~~\n'

----------------------------------------------------------------------

This removes the debugging output from the captured stdout text
so the assertion is done properly